package org.veritasopher.senizweb.core.exception;

import org.antlr.v4.runtime.misc.ParseCancellationException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseBody;
import org.veritasopher.senizweb.core.dictionary.ResponseCode;
import org.veritasopher.senizweb.core.response.Response;

/**
 * @Author Yepeng Ding
 * @Date 12/29/2019
 */
@ControllerAdvice
public class SystemExceptionHandler {
    private final static Logger logger = LoggerFactory.getLogger(SystemExceptionHandler.class);

    @ResponseBody
    @ExceptionHandler(value = SystemException.class)
    public Response systemExceptionHandler(SystemException e) {
        logger.error(e.getMessage());
        return Response.failure(e.getCode(), e.getMessage());
    }

    @ResponseBody
    @ExceptionHandler(value = ParseCancellationException.class)
    public Response parsingExceptionHandler(ParseCancellationException e) {
        logger.error(e.getMessage());
        return Response.failure(ResponseCode.FAILURE, e.getMessage());
    }

    @ResponseBody
    @ExceptionHandler(value = Exception.class)
    public Response errorHandler(Exception e) {
        logger.error(e.getMessage());
        return Response.failure("Internal Error.");
    }


}
